- eliottree.py
> Add child tree nodes to the correct parent to construct a real tree.

- eliottree.py
Closes issue #7.
Thanks to @itamarst for the patch.
> Fix regular messages causing an error.

- README.md
- eliot_tree.py
Add an option to disable truncating long values. Closes issue #12.
> Add an option to disable truncating long values. (closes issue #12)

- eliottree/_cli.py
- eliottree/test/test_tree.py
- eliottree/tree.py
Fixes #28.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/jonathanj/eliottree/29)
> Insert fake missing start tasks when the start task is in fact missing.

- eliottree/_cli.py
- eliottree/test/test_cli.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/jonathanj/eliottree/30)
> Fix two regressions in command-line functionality, and add tests to catch future regressions

- README.rst
- eliottree/_cli.py
- eliottree/test/test_cli.py
Fixes #31.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/jonathanj/eliottree/32)
> Parse and display timestamps as UTC when rendering human-readable values.

- LICENSE
- setup.py
Fixes #33.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/jonathanj/eliottree/34)
> Release 15.3.0

- .travis.yml
- eliottree/_cli.py
- eliottree/_compat.py
- eliottree/render.py
- eliottree/test/test_cli.py
- eliottree/test/test_compat.py
- eliottree/test/test_render.py
- eliottree/test/test_tree.py
- eliottree/tree.py
- setup.py
- tox.ini
Fixes #35.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/jonathanj/eliottree/36)
> Make eliot-tree run under Python3.5.

- README.rst
- eliottree/_cli.py
- eliottree/format.py
- eliottree/render.py
- eliottree/test/matchers.py
- eliottree/test/test_cli.py
- eliottree/test/test_format.py
- eliottree/test/test_render.py
- eliottree/tree.py
- setup.py
Fixes #19.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonathanj/eliottree/48)
> Use `tree-format` instead of writing our own, and colorize output.

- eliottree/__init__.py
- eliottree/_cli.py
- eliottree/test/tasks.py
- eliottree/test/test_cli.py
- eliottree/test/test_render.py
- eliottree/tree.py
Fixes #42.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonathanj/eliottree/50)
> Provide some context for parsing and merging errors.

- eliottree/_render.py
- eliottree/test/test_render.py
Fixes #54.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonathanj/eliottree/55)
> Color the action start and end statuses the same way.

- NEWS.rst
- eliottree/__init__.py
- eliottree/newsfragments/.gitignore
- eliottree/newsfragments/19.feature
- eliottree/newsfragments/35.bugfix
- eliottree/newsfragments/38.feature
- eliottree/newsfragments/39.bugfix
- eliottree/newsfragments/42.feature
- eliottree/newsfragments/44.feature
- eliottree/newsfragments/46.misc
- eliottree/newsfragments/52.feature
- eliottree/newsfragments/54.misc
- eliottree/newsfragments/56.misc
- towncrier.ini
Fixes #56.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonathanj/eliottree/57)
> Use towncrier.

- NEWS.rst
- eliottree/__init__.py
- eliottree/newsfragments/19.feature
- eliottree/newsfragments/35.bugfix
- eliottree/newsfragments/38.feature
- eliottree/newsfragments/39.bugfix
- eliottree/newsfragments/42.feature
- eliottree/newsfragments/44.feature
- eliottree/newsfragments/46.misc
- eliottree/newsfragments/52.feature
- eliottree/newsfragments/54.misc
- eliottree/newsfragments/56.misc
- setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonathanj/eliottree/58)
> Release 17.0.0.

- eliottree/filter.py
- eliottree/test/test_filter.py
Use a public import that hasn't been deprecated yet.
Fixes #60.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonathanj/eliottree/61)
> Fix eliot-tree being broken with `iso8601` 0.1.12.

- NEWS.rst
- eliottree/__init__.py
- setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonathanj/eliottree/62)
> Release 17.1.0

- NEWS.rst
- pyproject.toml
- towncrier.ini
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonathanj/eliottree/71)
> Release 18.0.0.

- NEWS.rst
- src/eliottree/newsfragments/72.feature
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonathanj/eliottree/74)
> Release 18.1.0.

- src/eliottree/_render.py
- src/eliottree/test/test_render.py
- src/eliottree/tree_format/_text.py
Hi, I created a new PR for the unicode issue with fixed tests.
Thank you for review.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonathanj/eliottree/102)
> Fix unicode error

- NEWS.rst
- src/eliottree/newsfragments/95.bugfix
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonathanj/eliottree/103)
> Release 21.0.0

- .github/workflows/pythonpackage.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonathanj/eliottree/108)
> ci: Drop unsupported versions of Python
